name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: Run script
        run: |
          echo "This is a script that takes two arguments:"
          echo "Argument 1: $1"
          echo "Argument 2: $2"
      - name: Print inline text
        run: > 
          echo "This is an inline echo command.
          some text
          another text"